#ifndef CPU_GPU_COMMON
#define CPU_GPU_COMMON

#define CULLING_THREADS_X 64
#define CULLING_THREADS_Y 1
#define CULLING_THREADS_Z 1

#define HIZ_THREADS_X 8
#define HIZ_THREADS_Y 8
#define HIZ_THREADS_Z 1

// for consoles, i.e. PS5/PS4/XBOXes, group sizes should be 64
//#define SWR_TRIANGLE_THREADS_X 64
#define SWR_TRIANGLE_THREADS_X 256
#define SWR_TRIANGLE_THREADS_Y 1
#define SWR_TRIANGLE_THREADS_Z 1

#define SWR_BIG_TRIANGLE_THREADS_X 8
#define SWR_BIG_TRIANGLE_THREADS_Y 8
#define SWR_BIG_TRIANGLE_THREADS_Z 1

#define MESHLET_SIZE 256

#define TRIANGLES_PER_THREAD ((MESHLET_SIZE) / (SWR_TRIANGLE_THREADS_X))
#define SWR_THREAD_GROUPS_Y ((MESHLET_SIZE) / (SWR_TRIANGLE_THREADS_X))

#define MAX_CASCADES_COUNT 8
// 1 is for main camera
#define MAX_FRUSTUMS_COUNT (1 + (MAX_CASCADES_COUNT))

#endif // CPU_GPU_COMMON
